services:
  backend:
    build: ./backend
    environment:
      ALLOWED_ORIGIN: "${SITE_DOMAIN}"
    volumes:
      - ${DATABASE_PATH}:/usr/src/hll/db

  frontend:
    build: ./frontend
    environment:
      ORIGIN: "${SITE_DOMAIN}" # required by adapter-node 

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
    environment:
      SITE_DOMAIN: "${SITE_DOMAIN}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
